modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: []
      no_follow_redirects: false
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: false
      fail_if_not_ssl: false
      fail_if_ssl: false

  tcp_connect:
    prober: tcp
    timeout: 5s

  dns_a:
    prober: dns
    timeout: 5s
    dns:
      query_name: "example.com"
      query_type: "A"
      valid_rcodes: ["NOERROR"]

  icmp_ping:
    prober: icmp
    timeout: 3s
