global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:8080

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - target_label: __address__
        replacement: blackbox-exporter:9115

      - source_labels: [__param_target]
        target_label: instance
